# Generated by Django 5.2.8 on 2026-01-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Urgência'),
        ),
    ]
