# Generated by Django 5.2.8 on 2026-01-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.TextField(blank=True, null=True, verbose_name='Resolução'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em'),
        ),
    ]
