# Generated by Django 5.2.8 on 2026-01-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_ticket_type_ticketattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Telefone')),
                ('original_input', models.CharField(blank=True, max_length=32, verbose_name='Entrada original')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
            ],
            options={
                'verbose_name': 'Destinatário WhatsApp',
                'verbose_name_plural': 'Destinatários WhatsApp',
                'ordering': ['-added_at'],
            },
        ),
    ]
