# Generated by Django 5.2.8 on 2026-01-30 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_working_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Criação'), ('status_change', 'Mudança de status'), ('comment', 'Comentário'), ('working_user', 'Responsável adicional')], max_length=30, verbose_name='Tipo do evento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(blank=True, choices=[('new', 'Novo'), ('in_progress', 'Em andamento'), ('awaiting', 'Aguardando resposta'), ('resolved', 'Resolvido')], max_length=20, null=True, verbose_name='Status relacionado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Evento de chamado',
                'verbose_name_plural': 'Eventos de chamados',
                'ordering': ['-timestamp'],
            },
        ),
    ]
